services:
  main_bot:
    build:
      context: .
    env_file:
      - .env
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@yandex.ru
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: unless-stopped
    depends_on:
     - postgres

volumes:
  postgres_data:
  pgadmin: